fields:
  'image:alt':
    solr: 'imagealt'
    type: 'text'
  'description':
    solr: 'description'
    type: 'text'
  'keywords':
    solr: 'keywords'
    type: 'text'
  'image':
    solr: 'image'
    type: 'text'
  'startDate':
    solr: 'startDate'
    type: 'date'
  'endDate':
    solr: 'endDate'
    type: 'date'
  'duration':
    solr: 'duration'
    type: 'text'
  'location':
    solr: 'location'
    type: 'text'
  'eventStatus':
    type: 'text'
  'content':
    solr: 'content'
    type: 'text'
  'name':
    solr: 'title'
    type: 'text'
    
#id_field: 'image'

regex_file: "regex-urlfilter.txt"

solr_index: ''
seed_file: "seed.txt"
